// CONNECTION
export const CONNECTION_REQUEST = "CONNECTION_REQUEST"
export const CONNECTION_SUCCESS = "CONNECTION_SUCCESS"
export const CONNECTION_FAILURE = "CONNECTION_FAILURE"

// COIN Data

export const COIN_DATA = "COIN_DATA"
export const COIN_DATA_SAVE = "COIN_DATA_SAVE"
export const COIN_DATA_FAILURE = "COIN_DATA_FAILURE"